/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandsignup;

/**
 *
 * @author Montassar
 */
public class choix_admin extends javax.swing.JFrame {

    /**
     * Creates new form choix
     */
    public choix_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LogoutBtn = new javax.swing.JButton();
        AffectationBtn = new javax.swing.JButton();
        TacheBtn = new javax.swing.JButton();
        projetBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BACKBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choix_Interface");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LogoutBtn.setBackground(new java.awt.Color(255, 51, 51));
        LogoutBtn.setText("LOGOUT");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        AffectationBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AffectationBtn.setForeground(new java.awt.Color(0, 102, 204));
        AffectationBtn.setText("AFFECTATION");
        AffectationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AffectationBtnActionPerformed(evt);
            }
        });

        TacheBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TacheBtn.setForeground(new java.awt.Color(0, 102, 204));
        TacheBtn.setText("TACHE");
        TacheBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TacheBtnActionPerformed(evt);
            }
        });

        projetBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        projetBtn.setForeground(new java.awt.Color(0, 102, 204));
        projetBtn.setText("PROJET");
        projetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projetBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Choix_Interface");

        BACKBtn.setText("BACK");
        BACKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BACKBtn)
                        .addGap(137, 137, 137)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(projetBtn)
                        .addGap(71, 71, 71)
                        .addComponent(TacheBtn)
                        .addGap(67, 67, 67)
                        .addComponent(AffectationBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(LogoutBtn)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BACKBtn)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AffectationBtn)
                    .addComponent(TacheBtn)
                    .addComponent(projetBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:

        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void TacheBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TacheBtnActionPerformed
        Tache_interface View2Frame = new Tache_interface();
        View2Frame.setVisible(true);
        View2Frame.pack();
        View2Frame.setLocationRelativeTo(null); 
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_TacheBtnActionPerformed

    private void AffectationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AffectationBtnActionPerformed
        Affectation_interface affectation_interfaceFrame = new Affectation_interface();
        affectation_interfaceFrame.setVisible(true);
        affectation_interfaceFrame.pack();
        affectation_interfaceFrame.setLocationRelativeTo(null);         // TODO add your handling code here:
    }//GEN-LAST:event_AffectationBtnActionPerformed

    private void projetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projetBtnActionPerformed
        Projet_interface View1Frame = new Projet_interface();
        View1Frame.setVisible(true);
        View1Frame.pack();
        View1Frame.setLocationRelativeTo(null); 
        this.dispose();   
        // TODO add your handling code here:
    }//GEN-LAST:event_projetBtnActionPerformed

    private void BACKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKBtnActionPerformed
        Home HomeFrame = new Home();
        HomeFrame.setVisible(true);
        HomeFrame.pack();
        HomeFrame.setLocationRelativeTo(null);
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_BACKBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choix_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choix_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choix_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choix_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new choix_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AffectationBtn;
    private javax.swing.JButton BACKBtn;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton TacheBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton projetBtn;
    // End of variables declaration//GEN-END:variables
}
